footer and join us page
zgzgorg/yj.zgzg.io pull request #175
Opened 2023-04-28 04:56 UTC by MaggieRepo

您好， 我更新了Join us page和把footer 的位置又调整了下。 （直挂云帆的照片和二维码的照片我没有看到链接就skip了带有这两个照片的部分 ） 有问题的话我再改，谢谢！

2023-04-28 06:53 UTC, tslmy requested changes

2023-04-28 06:53 UTC, tslmy commented on _layouts/join.html
> +    </div>
下面的tabs有显示除了云集以外的项目，但是这里的hero 横幅专门说的是云集，这样没问题吗？

![image](https://user-images.githubusercontent.com/594058/235075050-44e918cf-c608-4405-844a-c3d22489a2a8.png)

在目前公开的版本里，这里是几乎空白的，就不会造成这种歧义：

![image](https://user-images.githubusercontent.com/594058/235075889-5b314d81-9e02-4ae8-be78-9697343be457.png)

不过我不记得最初的设计稿了，是有人这样特意要求的吗？

2023-04-28 06:53 UTC, tslmy commented on _layouts/join.html
> +    {{ content }}
这样的话，这个标题距离卡片顶边的距离就没了：

![image](https://user-images.githubusercontent.com/594058/235075418-3716cdc1-41b1-4025-aec0-03667e89719d.png)

这条 CSS rule 在这里：
![image](https://user-images.githubusercontent.com/594058/235075580-a56b296d-569a-4957-87b7-9c32d9e6bf2c.png)

2023-05-22 02:39 UTC, yyf1997keykeyup approved these changes
LGTM

2023-05-22 02:40 UTC, merged